link_space: https://www.google.com
link_facebook: "https://www.facebook.com"
name_max: 50
phone_min: 10
phone_max: 11
email_max: 255
password_min: 6
remember_me: "1"
google_maps_api_key: AIzaSyCFOI6IXI1KEcs7hXeHlOasMIeKWLnRnf8
password_expired: 2
